[package]
name = "archer"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "0.33.2"
pollster = "0.4.0"
sdl2 = "0.37"
wgpu = "25.0.2"
bytemuck = { version = "1.14", features = ["derive"] }

